
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjohfhpkgubjeraxeuqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqb2hmaHBrZ3ViamVyYXhldXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODYxMzgsImV4cCI6MjA1Nzg2MjEzOH0.YEzMXD_0Ta1qo5BIiuSRjcRWItAcCZZgFS5-1zv0p8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure client with options for better network resilience
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (...args) => {
      // Add custom headers or modify fetch behavior here if needed
      return fetch(...args);
    },
  },
  realtime: {
    timeout: 60000, // Increase timeout to 60 seconds for better realtime connections
  },
});

// Network connectivity helper function (can be used across the app)
export const checkNetworkConnectivity = async (): Promise<boolean> => {
  try {
    // Simple health check to verify Supabase connection
    const { data, error } = await supabase.from('buildings').select('id').limit(1);
    return !error;
  } catch (e) {
    console.error("Network connectivity check failed:", e);
    return false;
  }
};
